name: imw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.10
  - cudatoolkit=12.1
  - pytorch=2.2.1
  - torchvision=0.17.1
  - torchmetrics=0.6.0
  - pytorch-lightning=1.4.9
  - pip
  - pip:
      - -r requirements.txt