name: imw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.4
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchmetrics=0.6.0
  - pytorch-lightning=1.4.9
  - pip
  - pip:
      - -r requirements.txt